/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * open-agents-platform backend REST API
 * Plain-REST surface of the agent backend (`packages/agent-backend`, port
 * 41080) as consumed by the agent frontend SPA (`packages/agent-frontend`,
 * port 41173, cross-origin via CORS).
 *
 * **Out of scope — do not add here:** the flue agent conversation endpoint
 * (`GET /agents/:name/:id`). It uses flue's Durable Streams protocol
 * (offset / reconnect / SSE observation), not standard REST, and stays on
 * `@flue/sdk` `createFlueClient`. Note that in this platform every agent
 * conversation is READ-ONLY over HTTP (GET/HEAD only, for live observation);
 * the sole write path into a conversation is `POST /channels/{id}/messages`,
 * which dispatches in-process.
 *
 * OpenAPI spec version: 0.0.0
 */
import type { Key } from "swr";
import type { SWRMutationConfiguration } from "swr/mutation";
import useSWRMutation from "swr/mutation";

import type { CreateSession200, CreateSession400, CreateSessionBody } from "../schemas";

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

export type createSessionResponse200 = {
  data: CreateSession200;
  status: 200;
};

export type createSessionResponse400 = {
  data: CreateSession400;
  status: 400;
};

export type createSessionResponseSuccess = createSessionResponse200 & {
  headers: Headers;
};
export type createSessionResponseError = createSessionResponse400 & {
  headers: Headers;
};

export type createSessionResponse = createSessionResponseSuccess | createSessionResponseError;

export const getCreateSessionUrl = () => {
  return `http://localhost:41080/session`;
};

/**
 * Unauthenticated bootstrap endpoint. Returns an HMAC-SHA256-signed,
 * expiring app-session token. The request body is optional — all of its
 * fields are optional, so an absent body (or `{}`) yields a freshly
 * generated session id. Pass `{ "sessionId": "..." }` to re-issue a token
 * for an existing session. A body that is present but is not valid JSON is
 * rejected by the generated request validator with 400.
 * @summary Issue an app-session bearer token
 */
export const createSession = async (
  createSessionBody?: CreateSessionBody,
  options?: RequestInit,
): Promise<createSessionResponse> => {
  const res = await fetch(getCreateSessionUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createSessionBody),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: createSessionResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as createSessionResponse;
};

export const getCreateSessionMutationFetcher = (options?: RequestInit) => {
  return (_: Key, { arg }: { arg: CreateSessionBody | undefined }) => {
    return createSession(arg, options);
  };
};
export const getCreateSessionMutationKey = () => [`http://localhost:41080/session`] as const;

export type CreateSessionMutationResult = NonNullable<Awaited<ReturnType<typeof createSession>>>;

/**
 * @summary Issue an app-session bearer token
 */
export const useCreateSession = <TError = Promise<CreateSession400>>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof createSession>>,
    TError,
    Key,
    CreateSessionBody | undefined,
    Awaited<ReturnType<typeof createSession>>
  > & { swrKey?: string };
  fetch?: RequestInit;
}) => {
  const { swr: swrOptions, fetch: fetchOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getCreateSessionMutationKey();
  const swrFn = getCreateSessionMutationFetcher(fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};
