/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * open-agents-platform backend REST API
 * Plain-REST surface of the agent backend (`packages/agent-backend`, port
 * 41080) as consumed by the agent frontend SPA (`packages/agent-frontend`,
 * port 41173, cross-origin via CORS).
 *
 * **Out of scope — do not add here:** the flue agent conversation endpoint
 * (`GET /agents/:name/:id`). It uses flue's Durable Streams protocol
 * (offset / reconnect / SSE observation), not standard REST, and stays on
 * `@flue/sdk` `createFlueClient`. Note that in this platform every agent
 * conversation is READ-ONLY over HTTP (GET/HEAD only, for live observation);
 * the sole write path into a conversation is `POST /channels/{id}/messages`,
 * which dispatches in-process.
 *
 * OpenAPI spec version: 0.0.0
 */

import type { Key, SWRConfiguration } from "swr";
import useSwr from "swr";

import type { GetHealth200 } from "../schemas";

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

export type getHealthResponse200 = {
  data: GetHealth200;
  status: 200;
};

export type getHealthResponseSuccess = getHealthResponse200 & {
  headers: Headers;
};

export type getHealthResponse = getHealthResponseSuccess;

export const getGetHealthUrl = () => {
  return `http://localhost:41080/health`;
};

/**
 * Reports service liveness and whether a live LLM key is configured.
 * Not called by the SPA — intended for smoke tests and monitoring.
 * @summary Liveness probe
 */
export const getHealth = async (options?: RequestInit): Promise<getHealthResponse> => {
  const res = await fetch(getGetHealthUrl(), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getHealthResponse["data"] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as getHealthResponse;
};

export const getGetHealthKey = () => [`http://localhost:41080/health`] as const;

export type GetHealthQueryResult = NonNullable<Awaited<ReturnType<typeof getHealth>>>;

/**
 * @summary Liveness probe
 */
export const useGetHealth = <TError = Promise<unknown>>(options?: {
  swr?: SWRConfiguration<Awaited<ReturnType<typeof getHealth>>, TError> & {
    swrKey?: Key;
    enabled?: boolean;
  };
  fetch?: RequestInit;
}) => {
  const { swr: swrOptions, fetch: fetchOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false;
  const swrKey = swrOptions?.swrKey ?? (() => (isEnabled ? getGetHealthKey() : null));
  const swrFn = () => getHealth(fetchOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};
