/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * open-agents-platform backend REST API
 * Plain-REST surface of the agent backend (`packages/agent-backend`, port
 * 41080) as consumed by the agent frontend SPA (`packages/agent-frontend`,
 * port 41173, cross-origin via CORS).
 *
 * **Out of scope — do not add here:** the flue agent conversation endpoint
 * (`GET /agents/:name/:id`). It uses flue's Durable Streams protocol
 * (offset / reconnect / SSE observation), not standard REST, and stays on
 * `@flue/sdk` `createFlueClient`. Note that in this platform every agent
 * conversation is READ-ONLY over HTTP (GET/HEAD only, for live observation);
 * the sole write path into a conversation is `POST /channels/{id}/messages`,
 * which dispatches in-process.
 *
 * OpenAPI spec version: 0.0.0
 */
import { createFactory } from "hono/factory";
import { zValidator } from "../validator";
import type {
  CreateChannelContext,
  CreateChannelMemberContext,
  CreateChannelMessageContext,
  DeleteChannelContext,
  DeleteChannelMemberContext,
  GetChannelsContext,
  UpdateChannelContext,
} from "./channels.context";
import {
  CreateChannelBody,
  CreateChannelMemberBody,
  CreateChannelMemberParams,
  CreateChannelMessageBody,
  CreateChannelMessageParams,
  DeleteChannelMemberParams,
  DeleteChannelParams,
  GetChannelsResponse,
  UpdateChannelBody,
  UpdateChannelParams,
  UpdateChannelResponse,
} from "./channels.zod";

const factory = createFactory();
export const getChannelsHandlers = factory.createHandlers(
  zValidator("response", GetChannelsResponse),
  async (_c: GetChannelsContext) => {},
);
export const createChannelHandlers = factory.createHandlers(
  zValidator("json", CreateChannelBody),
  async (_c: CreateChannelContext) => {},
);
export const updateChannelHandlers = factory.createHandlers(
  zValidator("param", UpdateChannelParams),
  zValidator("json", UpdateChannelBody),
  zValidator("response", UpdateChannelResponse),
  async (_c: UpdateChannelContext) => {},
);
export const deleteChannelHandlers = factory.createHandlers(
  zValidator("param", DeleteChannelParams),
  async (_c: DeleteChannelContext) => {},
);
export const createChannelMemberHandlers = factory.createHandlers(
  zValidator("param", CreateChannelMemberParams),
  zValidator("json", CreateChannelMemberBody),
  async (_c: CreateChannelMemberContext) => {},
);
export const deleteChannelMemberHandlers = factory.createHandlers(
  zValidator("param", DeleteChannelMemberParams),
  async (_c: DeleteChannelMemberContext) => {},
);
export const createChannelMessageHandlers = factory.createHandlers(
  zValidator("param", CreateChannelMessageParams),
  zValidator("json", CreateChannelMessageBody),
  async (_c: CreateChannelMessageContext) => {},
);
