/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * open-agents-platform backend REST API
 * Plain-REST surface of the agent backend (`packages/agent-backend`, port
 * 41080) as consumed by the agent frontend SPA (`packages/agent-frontend`,
 * port 41173, cross-origin via CORS).
 *
 * **Out of scope — do not add here:** the flue agent conversation endpoint
 * (`GET /agents/:name/:id`). It uses flue's Durable Streams protocol
 * (offset / reconnect / SSE observation), not standard REST, and stays on
 * `@flue/sdk` `createFlueClient`. Note that in this platform every agent
 * conversation is READ-ONLY over HTTP (GET/HEAD only, for live observation);
 * the sole write path into a conversation is `POST /channels/{id}/messages`,
 * which dispatches in-process.
 *
 * OpenAPI spec version: 0.0.0
 */
import { z as zod } from "zod";

export const GetChannelsResponse = zod.object({
  channels: zod
    .array(
      zod.object({
        id: zod.string().describe("Server-generated UUID."),
        name: zod.string().describe("Channel name shown in the sidebar."),
        goal: zod
          .string()
          .optional()
          .describe(
            "Optional goal text. Embedded in every dispatch input so member agents and the orchestrator know what the channel is working toward; absent = no goal set.",
          ),
        createdAt: zod.string().describe("Creation timestamp (ISO 8601)."),
        members: zod
          .array(
            zod.object({
              id: zod.string().describe("Server-generated member row id."),
              configId: zod
                .string()
                .describe(
                  "The invited agent's AgentConfig id. The member's conversation instance id is `{configId}__channel-{channelId}`.",
                ),
              name: zod
                .string()
                .describe("The agent's display name (denormalized from its AgentConfig)."),
              role: zod
                .string()
                .optional()
                .describe(
                  "The agent's job-title label (denormalized from its AgentConfig); absent = no role set.",
                ),
              createdAt: zod.string().describe("Invitation timestamp (ISO 8601)."),
            }),
          )
          .describe("Invited agents, oldest first."),
      }),
    )
    .describe("All stored channels, newest first, with members embedded. Shared across sessions."),
});

export const createChannelBodyNameMax = 100;

export const createChannelBodyGoalMax = 2000;

export const CreateChannelBody = zod.object({
  name: zod.string().min(1).max(createChannelBodyNameMax).describe("Channel name."),
  goal: zod
    .string()
    .min(1)
    .max(createChannelBodyGoalMax)
    .optional()
    .describe("Optional goal text."),
});

export const CreateChannelResponse = zod.object({
  id: zod.string().describe("Server-generated UUID."),
  name: zod.string().describe("Channel name shown in the sidebar."),
  goal: zod
    .string()
    .optional()
    .describe(
      "Optional goal text. Embedded in every dispatch input so member agents and the orchestrator know what the channel is working toward; absent = no goal set.",
    ),
  createdAt: zod.string().describe("Creation timestamp (ISO 8601)."),
  members: zod
    .array(
      zod.object({
        id: zod.string().describe("Server-generated member row id."),
        configId: zod
          .string()
          .describe(
            "The invited agent's AgentConfig id. The member's conversation instance id is `{configId}__channel-{channelId}`.",
          ),
        name: zod
          .string()
          .describe("The agent's display name (denormalized from its AgentConfig)."),
        role: zod
          .string()
          .optional()
          .describe(
            "The agent's job-title label (denormalized from its AgentConfig); absent = no role set.",
          ),
        createdAt: zod.string().describe("Invitation timestamp (ISO 8601)."),
      }),
    )
    .describe("Invited agents, oldest first."),
});

export const UpdateChannelParams = zod.object({
  id: zod.string().describe("Channel id."),
});

export const updateChannelBodyNameMax = 100;

export const updateChannelBodyGoalMax = 2000;

export const UpdateChannelBody = zod.object({
  name: zod
    .string()
    .min(1)
    .max(updateChannelBodyNameMax)
    .optional()
    .describe("New channel name (a name can never be cleared)."),
  goal: zod
    .string()
    .max(updateChannelBodyGoalMax)
    .nullish()
    .describe("Goal text; null clears the goal, omitted keeps it."),
});

export const UpdateChannelResponse = zod.object({
  id: zod.string().describe("Server-generated UUID."),
  name: zod.string().describe("Channel name shown in the sidebar."),
  goal: zod
    .string()
    .optional()
    .describe(
      "Optional goal text. Embedded in every dispatch input so member agents and the orchestrator know what the channel is working toward; absent = no goal set.",
    ),
  createdAt: zod.string().describe("Creation timestamp (ISO 8601)."),
  members: zod
    .array(
      zod.object({
        id: zod.string().describe("Server-generated member row id."),
        configId: zod
          .string()
          .describe(
            "The invited agent's AgentConfig id. The member's conversation instance id is `{configId}__channel-{channelId}`.",
          ),
        name: zod
          .string()
          .describe("The agent's display name (denormalized from its AgentConfig)."),
        role: zod
          .string()
          .optional()
          .describe(
            "The agent's job-title label (denormalized from its AgentConfig); absent = no role set.",
          ),
        createdAt: zod.string().describe("Invitation timestamp (ISO 8601)."),
      }),
    )
    .describe("Invited agents, oldest first."),
});

export const DeleteChannelParams = zod.object({
  id: zod.string().describe("Channel id."),
});

export const DeleteChannelResponse = zod.void();

export const CreateChannelMemberParams = zod.object({
  id: zod.string().describe("Channel id."),
});

export const CreateChannelMemberBody = zod.object({
  configId: zod.string().min(1).describe("The AgentConfig id of the agent to invite."),
});

export const CreateChannelMemberResponse = zod.object({
  id: zod.string().describe("Server-generated member row id."),
  configId: zod
    .string()
    .describe(
      "The invited agent's AgentConfig id. The member's conversation instance id is `{configId}__channel-{channelId}`.",
    ),
  name: zod.string().describe("The agent's display name (denormalized from its AgentConfig)."),
  role: zod
    .string()
    .optional()
    .describe(
      "The agent's job-title label (denormalized from its AgentConfig); absent = no role set.",
    ),
  createdAt: zod.string().describe("Invitation timestamp (ISO 8601)."),
});

export const DeleteChannelMemberParams = zod.object({
  id: zod.string().describe("Channel id."),
  memberId: zod.string().describe("Channel member id."),
});

export const DeleteChannelMemberResponse = zod.void();

export const CreateChannelMessageParams = zod.object({
  id: zod.string().describe("Channel id."),
});

export const createChannelMessageBodyTextMax = 4000;

export const CreateChannelMessageBody = zod.object({
  text: zod.string().min(1).max(createChannelMessageBodyTextMax).describe("The user's message."),
  memberId: zod
    .string()
    .optional()
    .describe(
      "Deliver directly to this member (the frontend resolves a leading @mention to a member id). Omitted: a single-member channel delivers to its member; a multi-member channel delivers to the orchestrator.",
    ),
});

export const CreateChannelMessageResponse = zod.void();
