/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * open-agents-platform backend REST API
 * Plain-REST surface of the agent backend (`packages/agent-backend`, port
 * 41080) as consumed by the agent frontend SPA (`packages/agent-frontend`,
 * port 41173, cross-origin via CORS).
 *
 * **Out of scope — do not add here:** the flue agent conversation endpoint
 * (`GET /agents/:name/:id`). It uses flue's Durable Streams protocol
 * (offset / reconnect / SSE observation), not standard REST, and stays on
 * `@flue/sdk` `createFlueClient`. Note that in this platform every agent
 * conversation is READ-ONLY over HTTP (GET/HEAD only, for live observation);
 * the sole write path into a conversation is `POST /channels/{id}/messages`,
 * which dispatches in-process.
 *
 * OpenAPI spec version: 0.0.0
 */
import type { Context, Env } from "hono";

import type {
  CreateChannelBody,
  CreateChannelMemberBody,
  CreateChannelMessageBody,
  UpdateChannelBody,
} from "../schemas";

export type GetChannelsContext<E extends Env = any> = Context<E, "/channels">;
export type CreateChannelContext<E extends Env = any> = Context<
  E,
  "/channels",
  { in: { json: CreateChannelBody }; out: { json: CreateChannelBody } }
>;
export type UpdateChannelContext<E extends Env = any> = Context<
  E,
  "/channels/:id",
  {
    in: {
      param: {
        id: string;
      };
      json: UpdateChannelBody;
    };
    out: {
      param: {
        id: string;
      };
      json: UpdateChannelBody;
    };
  }
>;
export type DeleteChannelContext<E extends Env = any> = Context<
  E,
  "/channels/:id",
  {
    in: {
      param: {
        id: string;
      };
    };
    out: {
      param: {
        id: string;
      };
    };
  }
>;
export type CreateChannelMemberContext<E extends Env = any> = Context<
  E,
  "/channels/:id/members",
  {
    in: {
      param: {
        id: string;
      };
      json: CreateChannelMemberBody;
    };
    out: {
      param: {
        id: string;
      };
      json: CreateChannelMemberBody;
    };
  }
>;
export type DeleteChannelMemberContext<E extends Env = any> = Context<
  E,
  "/channels/:id/members/:memberId",
  {
    in: {
      param: {
        id: string;
        memberId: string;
      };
    };
    out: {
      param: {
        id: string;
        memberId: string;
      };
    };
  }
>;
export type CreateChannelMessageContext<E extends Env = any> = Context<
  E,
  "/channels/:id/messages",
  {
    in: {
      param: {
        id: string;
      };
      json: CreateChannelMessageBody;
    };
    out: {
      param: {
        id: string;
      };
      json: CreateChannelMessageBody;
    };
  }
>;
