/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * open-agents-platform backend REST API
 * Plain-REST surface of the agent backend (`packages/agent-backend`, port
 * 42080) as consumed by the agent frontend SPA (`packages/agent-frontend`,
 * port 42173, cross-origin via CORS).
 *
 * **Out of scope — do not add here:** the flue agent conversation endpoint
 * (`GET /agents/:name/:id`). It uses flue's Durable Streams protocol
 * (offset / reconnect / SSE observation), not standard REST, and stays on
 * `@flue/sdk` `createFlueClient`. Note that in this platform every agent
 * conversation is READ-ONLY over HTTP (GET/HEAD only, for live observation);
 * the sole write path into a conversation is `POST /channels/{id}/messages`,
 * which dispatches in-process.
 *
 * OpenAPI spec version: 0.0.0
 */
import type { Context, Env } from "hono";

import type { CreateAgentConfigBody, UpdateAgentConfigBody } from "../schemas";

export type GetAgentConfigsContext<E extends Env = any> = Context<E, "/agent-configs">;
export type CreateAgentConfigContext<E extends Env = any> = Context<
  E,
  "/agent-configs",
  { in: { json: CreateAgentConfigBody }; out: { json: CreateAgentConfigBody } }
>;
export type UpdateAgentConfigContext<E extends Env = any> = Context<
  E,
  "/agent-configs/:id",
  {
    in: {
      param: {
        id: string;
      };
      json: UpdateAgentConfigBody;
    };
    out: {
      param: {
        id: string;
      };
      json: UpdateAgentConfigBody;
    };
  }
>;
export type DeleteAgentConfigContext<E extends Env = any> = Context<
  E,
  "/agent-configs/:id",
  {
    in: {
      param: {
        id: string;
      };
    };
    out: {
      param: {
        id: string;
      };
    };
  }
>;
