/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * open-agents-platform backend REST API
 * Plain-REST surface of the agent backend (`packages/agent-backend`, port
 * 41080) as consumed by the agent frontend SPA (`packages/agent-frontend`,
 * port 41173, cross-origin via CORS).
 *
 * **Out of scope — do not add here:** the flue agent conversation endpoint
 * (`GET /agents/:name/:id`). It uses flue's Durable Streams protocol
 * (offset / reconnect / SSE observation), not standard REST, and stays on
 * `@flue/sdk` `createFlueClient`. Note that in this platform every agent
 * conversation is READ-ONLY over HTTP (GET/HEAD only, for live observation);
 * the sole write path into a conversation is `POST /channels/{id}/messages`,
 * which dispatches in-process.
 *
 * OpenAPI spec version: 0.0.0
 */
import { z as zod } from "zod";

export const GetAgentConfigsResponse = zod.object({
  configs: zod
    .array(
      zod.object({
        id: zod
          .string()
          .describe(
            "Server-generated UUID (the `configId` half of the composite agent instance id).",
          ),
        name: zod
          .string()
          .describe(
            "Display name chosen by the end user. Unique across the catalog — it is the label the orchestrator's delegate tool and @mentions resolve against.",
          ),
        instructions: zod
          .string()
          .describe(
            "Free-form agent instructions written by the end user (applied as a lower-trust customization section under the operator hard rules).",
          ),
        role: zod
          .string()
          .optional()
          .describe('Job-title label (e.g. "Researcher"); absent = no role set.'),
        createdAt: zod.string().describe("Creation timestamp (ISO 8601)."),
      }),
    )
    .describe("All stored agents, newest first. The catalog is shared across sessions."),
});

export const createAgentConfigBodyNameMax = 100;

export const createAgentConfigBodyInstructionsMax = 4000;

export const createAgentConfigBodyRoleMax = 100;

export const CreateAgentConfigBody = zod.object({
  name: zod
    .string()
    .min(1)
    .max(createAgentConfigBodyNameMax)
    .describe("Display name. Must be unique across the catalog (409 otherwise)."),
  instructions: zod
    .string()
    .min(1)
    .max(createAgentConfigBodyInstructionsMax)
    .describe("Free-form agent instructions (applied as a lower-trust customization section)."),
  role: zod
    .string()
    .min(1)
    .max(createAgentConfigBodyRoleMax)
    .optional()
    .describe('Optional job-title label (e.g. "Researcher").'),
});

export const CreateAgentConfigResponse = zod.object({
  id: zod
    .string()
    .describe("Server-generated UUID (the `configId` half of the composite agent instance id)."),
  name: zod
    .string()
    .describe(
      "Display name chosen by the end user. Unique across the catalog — it is the label the orchestrator's delegate tool and @mentions resolve against.",
    ),
  instructions: zod
    .string()
    .describe(
      "Free-form agent instructions written by the end user (applied as a lower-trust customization section under the operator hard rules).",
    ),
  role: zod
    .string()
    .optional()
    .describe('Job-title label (e.g. "Researcher"); absent = no role set.'),
  createdAt: zod.string().describe("Creation timestamp (ISO 8601)."),
});

export const UpdateAgentConfigParams = zod.object({
  id: zod.string().describe("Agent configuration id."),
});

export const updateAgentConfigBodyNameMax = 100;

export const updateAgentConfigBodyInstructionsMax = 4000;

export const updateAgentConfigBodyRoleMax = 100;

export const UpdateAgentConfigBody = zod.object({
  name: zod
    .string()
    .min(1)
    .max(updateAgentConfigBodyNameMax)
    .optional()
    .describe("New display name (a name can never be cleared). Must stay unique (409 otherwise)."),
  instructions: zod
    .string()
    .min(1)
    .max(updateAgentConfigBodyInstructionsMax)
    .optional()
    .describe("New instructions (instructions can never be cleared)."),
  role: zod
    .string()
    .max(updateAgentConfigBodyRoleMax)
    .nullish()
    .describe("Job-title label; null clears the role, omitted keeps it."),
});

export const UpdateAgentConfigResponse = zod.object({
  id: zod
    .string()
    .describe("Server-generated UUID (the `configId` half of the composite agent instance id)."),
  name: zod
    .string()
    .describe(
      "Display name chosen by the end user. Unique across the catalog — it is the label the orchestrator's delegate tool and @mentions resolve against.",
    ),
  instructions: zod
    .string()
    .describe(
      "Free-form agent instructions written by the end user (applied as a lower-trust customization section under the operator hard rules).",
    ),
  role: zod
    .string()
    .optional()
    .describe('Job-title label (e.g. "Researcher"); absent = no role set.'),
  createdAt: zod.string().describe("Creation timestamp (ISO 8601)."),
});

export const DeleteAgentConfigParams = zod.object({
  id: zod.string().describe("Agent configuration id."),
});

export const DeleteAgentConfigResponse = zod.void();
