/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * open-agents-platform backend REST API
 * Plain-REST surface of the agent backend (`packages/agent-backend`, port
 * 42080) as consumed by the agent frontend SPA (`packages/agent-frontend`,
 * port 42173, cross-origin via CORS).
 *
 * **Out of scope — do not add here:** the flue agent conversation endpoint
 * (`GET /agents/:name/:id`). It uses flue's Durable Streams protocol
 * (offset / reconnect / SSE observation), not standard REST, and stays on
 * `@flue/sdk` `createFlueClient`. Note that in this platform every agent
 * conversation is READ-ONLY over HTTP (GET/HEAD only, for live observation);
 * the sole write path into a conversation is `POST /channels/{id}/messages`,
 * which dispatches in-process.
 *
 * OpenAPI spec version: 0.0.0
 */

import type { Arguments, Key, SWRConfiguration } from "swr";
import useSwr from "swr";
import type { SWRMutationConfiguration } from "swr/mutation";
import useSWRMutation from "swr/mutation";
import { customFetch } from ".././fetcher";
import type {
  CreateAgentConfig201,
  CreateAgentConfig400,
  CreateAgentConfig401,
  CreateAgentConfig409,
  CreateAgentConfigBody,
  DeleteAgentConfig401,
  DeleteAgentConfig404,
  GetAgentConfigs200,
  GetAgentConfigs401,
  UpdateAgentConfig200,
  UpdateAgentConfig400,
  UpdateAgentConfig401,
  UpdateAgentConfig404,
  UpdateAgentConfig409,
  UpdateAgentConfigBody,
} from "../schemas";

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export type getAgentConfigsResponse200 = {
  data: GetAgentConfigs200;
  status: 200;
};

export type getAgentConfigsResponse401 = {
  data: GetAgentConfigs401;
  status: 401;
};

export type getAgentConfigsResponseSuccess = getAgentConfigsResponse200 & {
  headers: Headers;
};
export type getAgentConfigsResponseError = getAgentConfigsResponse401 & {
  headers: Headers;
};

export type getAgentConfigsResponse = getAgentConfigsResponseSuccess | getAgentConfigsResponseError;

export const getGetAgentConfigsUrl = () => {
  return `http://localhost:42080/agent-configs`;
};

/**
 * Returns every stored agent (shared catalog — any session may invite any
 * agent into a channel; ownership enforcement is deferred until a real user
 * identity exists).
 * @summary List stored agents
 */
export const getAgentConfigs = async (options?: RequestInit): Promise<getAgentConfigsResponse> => {
  return customFetch<getAgentConfigsResponse>(getGetAgentConfigsUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetAgentConfigsKey = () => [`http://localhost:42080/agent-configs`] as const;

export type GetAgentConfigsQueryResult = NonNullable<Awaited<ReturnType<typeof getAgentConfigs>>>;

/**
 * @summary List stored agents
 */
export const useGetAgentConfigs = <TError = GetAgentConfigs401>(options?: {
  swr?: SWRConfiguration<Awaited<ReturnType<typeof getAgentConfigs>>, TError> & {
    swrKey?: Key;
    enabled?: boolean;
  };
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false;
  const swrKey = swrOptions?.swrKey ?? (() => (isEnabled ? getGetAgentConfigsKey() : null));
  const swrFn = () => getAgentConfigs(requestOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};
export type createAgentConfigResponse201 = {
  data: CreateAgentConfig201;
  status: 201;
};

export type createAgentConfigResponse400 = {
  data: CreateAgentConfig400;
  status: 400;
};

export type createAgentConfigResponse401 = {
  data: CreateAgentConfig401;
  status: 401;
};

export type createAgentConfigResponse409 = {
  data: CreateAgentConfig409;
  status: 409;
};

export type createAgentConfigResponseSuccess = createAgentConfigResponse201 & {
  headers: Headers;
};
export type createAgentConfigResponseError = (
  | createAgentConfigResponse400
  | createAgentConfigResponse401
  | createAgentConfigResponse409
) & {
  headers: Headers;
};

export type createAgentConfigResponse =
  | createAgentConfigResponseSuccess
  | createAgentConfigResponseError;

export const getCreateAgentConfigUrl = () => {
  return `http://localhost:42080/agent-configs`;
};

/**
 * Persists a user-created agent in the backend database. The `instructions`
 * text is free-form; at run time it is applied to the `custom` agent as a
 * sanitized, lower-trust customization section that never overrides the
 * operator hard rules. The name must be unique across the catalog — it is
 * the label the orchestrator's delegate tool and @mentions resolve against.
 * @summary Create an agent
 */
export const createAgentConfig = async (
  createAgentConfigBody: CreateAgentConfigBody,
  options?: RequestInit,
): Promise<createAgentConfigResponse> => {
  return customFetch<createAgentConfigResponse>(getCreateAgentConfigUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createAgentConfigBody),
  });
};

export const getCreateAgentConfigMutationFetcher = (
  options?: SecondParameter<typeof customFetch>,
) => {
  return (_: Key, { arg }: { arg: CreateAgentConfigBody }) => {
    return createAgentConfig(arg, options);
  };
};
export const getCreateAgentConfigMutationKey = () =>
  [`http://localhost:42080/agent-configs`] as const;

export type CreateAgentConfigMutationResult = NonNullable<
  Awaited<ReturnType<typeof createAgentConfig>>
>;

/**
 * @summary Create an agent
 */
export const useCreateAgentConfig = <
  TError = CreateAgentConfig400 | CreateAgentConfig401 | CreateAgentConfig409,
>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof createAgentConfig>>,
    TError,
    Key,
    CreateAgentConfigBody,
    Awaited<ReturnType<typeof createAgentConfig>>
  > & { swrKey?: string };
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getCreateAgentConfigMutationKey();
  const swrFn = getCreateAgentConfigMutationFetcher(requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};
export type updateAgentConfigResponse200 = {
  data: UpdateAgentConfig200;
  status: 200;
};

export type updateAgentConfigResponse400 = {
  data: UpdateAgentConfig400;
  status: 400;
};

export type updateAgentConfigResponse401 = {
  data: UpdateAgentConfig401;
  status: 401;
};

export type updateAgentConfigResponse404 = {
  data: UpdateAgentConfig404;
  status: 404;
};

export type updateAgentConfigResponse409 = {
  data: UpdateAgentConfig409;
  status: 409;
};

export type updateAgentConfigResponseSuccess = updateAgentConfigResponse200 & {
  headers: Headers;
};
export type updateAgentConfigResponseError = (
  | updateAgentConfigResponse400
  | updateAgentConfigResponse401
  | updateAgentConfigResponse404
  | updateAgentConfigResponse409
) & {
  headers: Headers;
};

export type updateAgentConfigResponse =
  | updateAgentConfigResponseSuccess
  | updateAgentConfigResponseError;

export const getUpdateAgentConfigUrl = (id: string) => {
  return `http://localhost:42080/agent-configs/${id}`;
};

/**
 * Updates a stored agent. Edits apply to live conversations on their next
 * message (the `custom` agent re-reads its config per delivered message).
 * @summary Update an agent's name, instructions, and/or role
 */
export const updateAgentConfig = async (
  id: string,
  updateAgentConfigBody: UpdateAgentConfigBody,
  options?: RequestInit,
): Promise<updateAgentConfigResponse> => {
  return customFetch<updateAgentConfigResponse>(getUpdateAgentConfigUrl(id), {
    ...options,
    method: "PATCH",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(updateAgentConfigBody),
  });
};

export const getUpdateAgentConfigMutationFetcher = (
  id: string,
  options?: SecondParameter<typeof customFetch>,
) => {
  return (_: Key, { arg }: { arg: UpdateAgentConfigBody }) => {
    return updateAgentConfig(id, arg, options);
  };
};
export const getUpdateAgentConfigMutationKey = (id: string) =>
  [`http://localhost:42080/agent-configs/${id}`] as const;

export type UpdateAgentConfigMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateAgentConfig>>
>;

/**
 * @summary Update an agent's name, instructions, and/or role
 */
export const useUpdateAgentConfig = <
  TError =
    | UpdateAgentConfig400
    | UpdateAgentConfig401
    | UpdateAgentConfig404
    | UpdateAgentConfig409,
>(
  id: string,
  options?: {
    swr?: SWRMutationConfiguration<
      Awaited<ReturnType<typeof updateAgentConfig>>,
      TError,
      Key,
      UpdateAgentConfigBody,
      Awaited<ReturnType<typeof updateAgentConfig>>
    > & { swrKey?: string };
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getUpdateAgentConfigMutationKey(id);
  const swrFn = getUpdateAgentConfigMutationFetcher(id, requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};
export type deleteAgentConfigResponse204 = {
  data: void;
  status: 204;
};

export type deleteAgentConfigResponse401 = {
  data: DeleteAgentConfig401;
  status: 401;
};

export type deleteAgentConfigResponse404 = {
  data: DeleteAgentConfig404;
  status: 404;
};

export type deleteAgentConfigResponseSuccess = deleteAgentConfigResponse204 & {
  headers: Headers;
};
export type deleteAgentConfigResponseError = (
  | deleteAgentConfigResponse401
  | deleteAgentConfigResponse404
) & {
  headers: Headers;
};

export type deleteAgentConfigResponse =
  | deleteAgentConfigResponseSuccess
  | deleteAgentConfigResponseError;

export const getDeleteAgentConfigUrl = (id: string) => {
  return `http://localhost:42080/agent-configs/${id}`;
};

/**
 * Deletes a stored agent. Channel memberships referencing it are removed in
 * the same transaction (Prisma relation onDelete Cascade), so every
 * composite instance id built from this config is rejected with 404 by the
 * conversation guard afterwards.
 * @summary Delete an agent
 */
export const deleteAgentConfig = async (
  id: string,
  options?: RequestInit,
): Promise<deleteAgentConfigResponse> => {
  return customFetch<deleteAgentConfigResponse>(getDeleteAgentConfigUrl(id), {
    ...options,
    method: "DELETE",
  });
};

export const getDeleteAgentConfigMutationFetcher = (
  id: string,
  options?: SecondParameter<typeof customFetch>,
) => {
  return (_: Key, __: { arg: Arguments }) => {
    return deleteAgentConfig(id, options);
  };
};
export const getDeleteAgentConfigMutationKey = (id: string) =>
  [`http://localhost:42080/agent-configs/${id}`] as const;

export type DeleteAgentConfigMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteAgentConfig>>
>;

/**
 * @summary Delete an agent
 */
export const useDeleteAgentConfig = <TError = DeleteAgentConfig401 | DeleteAgentConfig404>(
  id: string,
  options?: {
    swr?: SWRMutationConfiguration<
      Awaited<ReturnType<typeof deleteAgentConfig>>,
      TError,
      Key,
      Arguments,
      Awaited<ReturnType<typeof deleteAgentConfig>>
    > & { swrKey?: string };
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getDeleteAgentConfigMutationKey(id);
  const swrFn = getDeleteAgentConfigMutationFetcher(id, requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};
