/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * open-agents-platform backend REST API
 * Plain-REST surface of the agent backend (`packages/agent-backend`, port
 * 41080) as consumed by the agent frontend SPA (`packages/agent-frontend`,
 * port 41173, cross-origin via CORS).
 *
 * **Out of scope — do not add here:** the flue agent conversation endpoint
 * (`GET /agents/:name/:id`). It uses flue's Durable Streams protocol
 * (offset / reconnect / SSE observation), not standard REST, and stays on
 * `@flue/sdk` `createFlueClient`. Note that in this platform every agent
 * conversation is READ-ONLY over HTTP (GET/HEAD only, for live observation);
 * the sole write path into a conversation is `POST /channels/{id}/messages`,
 * which dispatches in-process.
 *
 * OpenAPI spec version: 0.0.0
 */
import { Hono } from "hono";
import {
  createAgentConfigHandlers,
  deleteAgentConfigHandlers,
  getAgentConfigsHandlers,
  updateAgentConfigHandlers,
} from "./handlers/agent-configs/agent-configs.handlers";
import {
  createChannelHandlers,
  createChannelMemberHandlers,
  createChannelMessageHandlers,
  deleteChannelHandlers,
  deleteChannelMemberHandlers,
  getChannelsHandlers,
  updateChannelHandlers,
} from "./handlers/channels/channels.handlers";
import { getHealthHandlers } from "./handlers/meta/meta.handlers";
import { createSessionHandlers } from "./handlers/session/session.handlers";

const app = new Hono()
  .get("/health", ...getHealthHandlers)
  .post("/session", ...createSessionHandlers)
  .get("/agent-configs", ...getAgentConfigsHandlers)
  .post("/agent-configs", ...createAgentConfigHandlers)
  .patch("/agent-configs/:id", ...updateAgentConfigHandlers)
  .delete("/agent-configs/:id", ...deleteAgentConfigHandlers)
  .get("/channels", ...getChannelsHandlers)
  .post("/channels", ...createChannelHandlers)
  .patch("/channels/:id", ...updateChannelHandlers)
  .delete("/channels/:id", ...deleteChannelHandlers)
  .post("/channels/:id/members", ...createChannelMemberHandlers)
  .delete("/channels/:id/members/:memberId", ...deleteChannelMemberHandlers)
  .post("/channels/:id/messages", ...createChannelMessageHandlers);

export default app;
