/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * open-agents-platform backend REST API
 * Plain-REST surface of the agent backend (`packages/agent-backend`, port
 * 41080) as consumed by the agent frontend SPA (`packages/agent-frontend`,
 * port 41173, cross-origin via CORS).
 *
 * **Out of scope — do not add here:** the flue agent conversation endpoint
 * (`GET /agents/:name/:id`). It uses flue's Durable Streams protocol
 * (offset / reconnect / SSE observation), not standard REST, and stays on
 * `@flue/sdk` `createFlueClient`. Note that in this platform every agent
 * conversation is READ-ONLY over HTTP (GET/HEAD only, for live observation);
 * the sole write path into a conversation is `POST /channels/{id}/messages`,
 * which dispatches in-process.
 *
 * OpenAPI spec version: 0.0.0
 */

export interface CreateAgentConfigRequest {
  /**
   * Display name. Must be unique across the catalog (409 otherwise).
   * @minLength 1
   * @maxLength 100
   */
  name: string;
  /**
   * Free-form agent instructions (applied as a lower-trust customization section).
   * @minLength 1
   * @maxLength 4000
   */
  instructions: string;
  /**
   * Optional job-title label (e.g. "Researcher").
   * @minLength 1
   * @maxLength 100
   */
  role?: string;
}
