/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * open-agents-platform backend REST API
 * Plain-REST surface of the agent backend (`packages/agent-backend`, port
 * 42080) as consumed by the agent frontend SPA (`packages/agent-frontend`,
 * port 42173, cross-origin via CORS).
 *
 * **Out of scope — do not add here:** the flue agent conversation endpoint
 * (`GET /agents/:name/:id`). It uses flue's Durable Streams protocol
 * (offset / reconnect / SSE observation), not standard REST, and stays on
 * `@flue/sdk` `createFlueClient`. Note that in this platform every agent
 * conversation is READ-ONLY over HTTP (GET/HEAD only, for live observation);
 * the sole write path into a conversation is `POST /channels/{id}/messages`,
 * which dispatches in-process.
 *
 * OpenAPI spec version: 0.0.0
 */

export type UpdateAgentConfigBody = {
  /**
   * New display name (a name can never be cleared). Must stay unique (409 otherwise).
   * @minLength 1
   * @maxLength 100
   */
  name?: string;
  /**
   * New instructions (instructions can never be cleared).
   * @minLength 1
   * @maxLength 4000
   */
  instructions?: string;
  /**
   * Job-title label; null clears the role, omitted keeps it.
   * @maxLength 100
   * @nullable
   */
  role?: string | null;
};
