/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * open-agents-platform backend REST API
 * Plain-REST surface of the agent backend (`packages/agent-backend`, port
 * 41080) as consumed by the agent frontend SPA (`packages/agent-frontend`,
 * port 41173, cross-origin via CORS).
 *
 * **Out of scope — do not add here:** the flue agent conversation endpoint
 * (`GET /agents/:name/:id`). It uses flue's Durable Streams protocol
 * (offset / reconnect / SSE observation), not standard REST, and stays on
 * `@flue/sdk` `createFlueClient`. Note that in this platform every agent
 * conversation is READ-ONLY over HTTP (GET/HEAD only, for live observation);
 * the sole write path into a conversation is `POST /channels/{id}/messages`,
 * which dispatches in-process.
 *
 * OpenAPI spec version: 0.0.0
 */

import type { Arguments, Key, SWRConfiguration } from "swr";
import useSwr from "swr";
import type { SWRMutationConfiguration } from "swr/mutation";
import useSWRMutation from "swr/mutation";
import { customFetch } from ".././fetcher";
import type {
  CreateChannel201,
  CreateChannel400,
  CreateChannel401,
  CreateChannelBody,
  CreateChannelMember201,
  CreateChannelMember400,
  CreateChannelMember401,
  CreateChannelMember404,
  CreateChannelMember409,
  CreateChannelMemberBody,
  CreateChannelMessage400,
  CreateChannelMessage401,
  CreateChannelMessage404,
  CreateChannelMessage409,
  CreateChannelMessageBody,
  DeleteChannel401,
  DeleteChannel404,
  DeleteChannelMember401,
  DeleteChannelMember404,
  GetChannels200,
  GetChannels401,
  UpdateChannel200,
  UpdateChannel400,
  UpdateChannel401,
  UpdateChannel404,
  UpdateChannelBody,
} from "../schemas";

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export type getChannelsResponse200 = {
  data: GetChannels200;
  status: 200;
};

export type getChannelsResponse401 = {
  data: GetChannels401;
  status: 401;
};

export type getChannelsResponseSuccess = getChannelsResponse200 & {
  headers: Headers;
};
export type getChannelsResponseError = getChannelsResponse401 & {
  headers: Headers;
};

export type getChannelsResponse = getChannelsResponseSuccess | getChannelsResponseError;

export const getGetChannelsUrl = () => {
  return `http://localhost:41080/channels`;
};

/**
 * Returns every stored channel, newest first, with invited members embedded
 * (including each member's denormalized name/role, so the sidebar and the
 * room render from this single request). Shared catalog — same
 * deferred-ownership stance as agent configs.
 * @summary List channels with their members
 */
export const getChannels = async (options?: RequestInit): Promise<getChannelsResponse> => {
  return customFetch<getChannelsResponse>(getGetChannelsUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetChannelsKey = () => [`http://localhost:41080/channels`] as const;

export type GetChannelsQueryResult = NonNullable<Awaited<ReturnType<typeof getChannels>>>;

/**
 * @summary List channels with their members
 */
export const useGetChannels = <TError = GetChannels401>(options?: {
  swr?: SWRConfiguration<Awaited<ReturnType<typeof getChannels>>, TError> & {
    swrKey?: Key;
    enabled?: boolean;
  };
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false;
  const swrKey = swrOptions?.swrKey ?? (() => (isEnabled ? getGetChannelsKey() : null));
  const swrFn = () => getChannels(requestOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};
export type createChannelResponse201 = {
  data: CreateChannel201;
  status: 201;
};

export type createChannelResponse400 = {
  data: CreateChannel400;
  status: 400;
};

export type createChannelResponse401 = {
  data: CreateChannel401;
  status: 401;
};

export type createChannelResponseSuccess = createChannelResponse201 & {
  headers: Headers;
};
export type createChannelResponseError = (createChannelResponse400 | createChannelResponse401) & {
  headers: Headers;
};

export type createChannelResponse = createChannelResponseSuccess | createChannelResponseError;

export const getCreateChannelUrl = () => {
  return `http://localhost:41080/channels`;
};

/**
 * Persists a channel (name + optional goal). The channel starts with no
 * members; invite agents via POST /channels/{id}/members.
 * @summary Create a channel
 */
export const createChannel = async (
  createChannelBody: CreateChannelBody,
  options?: RequestInit,
): Promise<createChannelResponse> => {
  return customFetch<createChannelResponse>(getCreateChannelUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createChannelBody),
  });
};

export const getCreateChannelMutationFetcher = (options?: SecondParameter<typeof customFetch>) => {
  return (_: Key, { arg }: { arg: CreateChannelBody }) => {
    return createChannel(arg, options);
  };
};
export const getCreateChannelMutationKey = () => [`http://localhost:41080/channels`] as const;

export type CreateChannelMutationResult = NonNullable<Awaited<ReturnType<typeof createChannel>>>;

/**
 * @summary Create a channel
 */
export const useCreateChannel = <TError = CreateChannel400 | CreateChannel401>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof createChannel>>,
    TError,
    Key,
    CreateChannelBody,
    Awaited<ReturnType<typeof createChannel>>
  > & { swrKey?: string };
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getCreateChannelMutationKey();
  const swrFn = getCreateChannelMutationFetcher(requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};
export type updateChannelResponse200 = {
  data: UpdateChannel200;
  status: 200;
};

export type updateChannelResponse400 = {
  data: UpdateChannel400;
  status: 400;
};

export type updateChannelResponse401 = {
  data: UpdateChannel401;
  status: 401;
};

export type updateChannelResponse404 = {
  data: UpdateChannel404;
  status: 404;
};

export type updateChannelResponseSuccess = updateChannelResponse200 & {
  headers: Headers;
};
export type updateChannelResponseError = (
  | updateChannelResponse400
  | updateChannelResponse401
  | updateChannelResponse404
) & {
  headers: Headers;
};

export type updateChannelResponse = updateChannelResponseSuccess | updateChannelResponseError;

export const getUpdateChannelUrl = (id: string) => {
  return `http://localhost:41080/channels/${id}`;
};

/**
 * Updates the channel name and/or the goal text shown in the room header.
 * The orchestrator and member agents pick up a changed goal on their next
 * message (their context is re-read per delivered message).
 * @summary Update a channel's name and/or goal
 */
export const updateChannel = async (
  id: string,
  updateChannelBody: UpdateChannelBody,
  options?: RequestInit,
): Promise<updateChannelResponse> => {
  return customFetch<updateChannelResponse>(getUpdateChannelUrl(id), {
    ...options,
    method: "PATCH",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(updateChannelBody),
  });
};

export const getUpdateChannelMutationFetcher = (
  id: string,
  options?: SecondParameter<typeof customFetch>,
) => {
  return (_: Key, { arg }: { arg: UpdateChannelBody }) => {
    return updateChannel(id, arg, options);
  };
};
export const getUpdateChannelMutationKey = (id: string) =>
  [`http://localhost:41080/channels/${id}`] as const;

export type UpdateChannelMutationResult = NonNullable<Awaited<ReturnType<typeof updateChannel>>>;

/**
 * @summary Update a channel's name and/or goal
 */
export const useUpdateChannel = <TError = UpdateChannel400 | UpdateChannel401 | UpdateChannel404>(
  id: string,
  options?: {
    swr?: SWRMutationConfiguration<
      Awaited<ReturnType<typeof updateChannel>>,
      TError,
      Key,
      UpdateChannelBody,
      Awaited<ReturnType<typeof updateChannel>>
    > & { swrKey?: string };
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getUpdateChannelMutationKey(id);
  const swrFn = getUpdateChannelMutationFetcher(id, requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};
export type deleteChannelResponse204 = {
  data: void;
  status: 204;
};

export type deleteChannelResponse401 = {
  data: DeleteChannel401;
  status: 401;
};

export type deleteChannelResponse404 = {
  data: DeleteChannel404;
  status: 404;
};

export type deleteChannelResponseSuccess = deleteChannelResponse204 & {
  headers: Headers;
};
export type deleteChannelResponseError = (deleteChannelResponse401 | deleteChannelResponse404) & {
  headers: Headers;
};

export type deleteChannelResponse = deleteChannelResponseSuccess | deleteChannelResponseError;

export const getDeleteChannelUrl = (id: string) => {
  return `http://localhost:41080/channels/${id}`;
};

/**
 * Removes the channel and (via cascade) its members. Agent conversations in
 * flue's store are left as-is — they are unreachable once the channel row is
 * gone.
 * @summary Delete a channel
 */
export const deleteChannel = async (
  id: string,
  options?: RequestInit,
): Promise<deleteChannelResponse> => {
  return customFetch<deleteChannelResponse>(getDeleteChannelUrl(id), {
    ...options,
    method: "DELETE",
  });
};

export const getDeleteChannelMutationFetcher = (
  id: string,
  options?: SecondParameter<typeof customFetch>,
) => {
  return (_: Key, __: { arg: Arguments }) => {
    return deleteChannel(id, options);
  };
};
export const getDeleteChannelMutationKey = (id: string) =>
  [`http://localhost:41080/channels/${id}`] as const;

export type DeleteChannelMutationResult = NonNullable<Awaited<ReturnType<typeof deleteChannel>>>;

/**
 * @summary Delete a channel
 */
export const useDeleteChannel = <TError = DeleteChannel401 | DeleteChannel404>(
  id: string,
  options?: {
    swr?: SWRMutationConfiguration<
      Awaited<ReturnType<typeof deleteChannel>>,
      TError,
      Key,
      Arguments,
      Awaited<ReturnType<typeof deleteChannel>>
    > & { swrKey?: string };
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getDeleteChannelMutationKey(id);
  const swrFn = getDeleteChannelMutationFetcher(id, requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};
export type createChannelMemberResponse201 = {
  data: CreateChannelMember201;
  status: 201;
};

export type createChannelMemberResponse400 = {
  data: CreateChannelMember400;
  status: 400;
};

export type createChannelMemberResponse401 = {
  data: CreateChannelMember401;
  status: 401;
};

export type createChannelMemberResponse404 = {
  data: CreateChannelMember404;
  status: 404;
};

export type createChannelMemberResponse409 = {
  data: CreateChannelMember409;
  status: 409;
};

export type createChannelMemberResponseSuccess = createChannelMemberResponse201 & {
  headers: Headers;
};
export type createChannelMemberResponseError = (
  | createChannelMemberResponse400
  | createChannelMemberResponse401
  | createChannelMemberResponse404
  | createChannelMemberResponse409
) & {
  headers: Headers;
};

export type createChannelMemberResponse =
  | createChannelMemberResponseSuccess
  | createChannelMemberResponseError;

export const getCreateChannelMemberUrl = (id: string) => {
  return `http://localhost:41080/channels/${id}/members`;
};

/**
 * Adds one user-created agent as a channel member. The agent's per-channel
 * conversation (`/agents/custom/{configId}__channel-{channelId}`) becomes
 * observable once its first message is dispatched.
 * @summary Invite an agent to the channel
 */
export const createChannelMember = async (
  id: string,
  createChannelMemberBody: CreateChannelMemberBody,
  options?: RequestInit,
): Promise<createChannelMemberResponse> => {
  return customFetch<createChannelMemberResponse>(getCreateChannelMemberUrl(id), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createChannelMemberBody),
  });
};

export const getCreateChannelMemberMutationFetcher = (
  id: string,
  options?: SecondParameter<typeof customFetch>,
) => {
  return (_: Key, { arg }: { arg: CreateChannelMemberBody }) => {
    return createChannelMember(id, arg, options);
  };
};
export const getCreateChannelMemberMutationKey = (id: string) =>
  [`http://localhost:41080/channels/${id}/members`] as const;

export type CreateChannelMemberMutationResult = NonNullable<
  Awaited<ReturnType<typeof createChannelMember>>
>;

/**
 * @summary Invite an agent to the channel
 */
export const useCreateChannelMember = <
  TError =
    | CreateChannelMember400
    | CreateChannelMember401
    | CreateChannelMember404
    | CreateChannelMember409,
>(
  id: string,
  options?: {
    swr?: SWRMutationConfiguration<
      Awaited<ReturnType<typeof createChannelMember>>,
      TError,
      Key,
      CreateChannelMemberBody,
      Awaited<ReturnType<typeof createChannelMember>>
    > & { swrKey?: string };
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getCreateChannelMemberMutationKey(id);
  const swrFn = getCreateChannelMemberMutationFetcher(id, requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};
export type deleteChannelMemberResponse204 = {
  data: void;
  status: 204;
};

export type deleteChannelMemberResponse401 = {
  data: DeleteChannelMember401;
  status: 401;
};

export type deleteChannelMemberResponse404 = {
  data: DeleteChannelMember404;
  status: 404;
};

export type deleteChannelMemberResponseSuccess = deleteChannelMemberResponse204 & {
  headers: Headers;
};
export type deleteChannelMemberResponseError = (
  | deleteChannelMemberResponse401
  | deleteChannelMemberResponse404
) & {
  headers: Headers;
};

export type deleteChannelMemberResponse =
  | deleteChannelMemberResponseSuccess
  | deleteChannelMemberResponseError;

export const getDeleteChannelMemberUrl = (id: string, memberId: string) => {
  return `http://localhost:41080/channels/${id}/members/${memberId}`;
};

/**
 * Removes the member. Its per-channel conversation is left in place so a
 * re-invite reattaches the same history.
 * @summary Remove an agent from the channel
 */
export const deleteChannelMember = async (
  id: string,
  memberId: string,
  options?: RequestInit,
): Promise<deleteChannelMemberResponse> => {
  return customFetch<deleteChannelMemberResponse>(getDeleteChannelMemberUrl(id, memberId), {
    ...options,
    method: "DELETE",
  });
};

export const getDeleteChannelMemberMutationFetcher = (
  id: string,
  memberId: string,
  options?: SecondParameter<typeof customFetch>,
) => {
  return (_: Key, __: { arg: Arguments }) => {
    return deleteChannelMember(id, memberId, options);
  };
};
export const getDeleteChannelMemberMutationKey = (id: string, memberId: string) =>
  [`http://localhost:41080/channels/${id}/members/${memberId}`] as const;

export type DeleteChannelMemberMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteChannelMember>>
>;

/**
 * @summary Remove an agent from the channel
 */
export const useDeleteChannelMember = <TError = DeleteChannelMember401 | DeleteChannelMember404>(
  id: string,
  memberId: string,
  options?: {
    swr?: SWRMutationConfiguration<
      Awaited<ReturnType<typeof deleteChannelMember>>,
      TError,
      Key,
      Arguments,
      Awaited<ReturnType<typeof deleteChannelMember>>
    > & { swrKey?: string };
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getDeleteChannelMemberMutationKey(id, memberId);
  const swrFn = getDeleteChannelMemberMutationFetcher(id, memberId, requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};
export type createChannelMessageResponse202 = {
  data: void;
  status: 202;
};

export type createChannelMessageResponse400 = {
  data: CreateChannelMessage400;
  status: 400;
};

export type createChannelMessageResponse401 = {
  data: CreateChannelMessage401;
  status: 401;
};

export type createChannelMessageResponse404 = {
  data: CreateChannelMessage404;
  status: 404;
};

export type createChannelMessageResponse409 = {
  data: CreateChannelMessage409;
  status: 409;
};

export type createChannelMessageResponseSuccess = createChannelMessageResponse202 & {
  headers: Headers;
};
export type createChannelMessageResponseError = (
  | createChannelMessageResponse400
  | createChannelMessageResponse401
  | createChannelMessageResponse404
  | createChannelMessageResponse409
) & {
  headers: Headers;
};

export type createChannelMessageResponse =
  | createChannelMessageResponseSuccess
  | createChannelMessageResponseError;

export const getCreateChannelMessageUrl = (id: string) => {
  return `http://localhost:41080/channels/${id}/messages`;
};

/**
 * Dispatches the message into the right agent conversation and responds on
 * admission (202):
 *
 * - `memberId` present (the frontend resolves a leading @mention): the
 *   message is delivered directly to that member agent.
 * - Channel has exactly one member: delivered directly to that member.
 * - Otherwise: delivered to the channel's `orchestrator` conversation; the
 *   orchestrator replies and/or delegates to members via its
 *   `delegate_to_member` tool.
 *
 * The message and the agents' replies appear in the per-channel
 * conversations, which the frontend observes live over SSE and merges
 * client-side.
 * @summary Post a message to the channel
 */
export const createChannelMessage = async (
  id: string,
  createChannelMessageBody: CreateChannelMessageBody,
  options?: RequestInit,
): Promise<createChannelMessageResponse> => {
  return customFetch<createChannelMessageResponse>(getCreateChannelMessageUrl(id), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createChannelMessageBody),
  });
};

export const getCreateChannelMessageMutationFetcher = (
  id: string,
  options?: SecondParameter<typeof customFetch>,
) => {
  return (_: Key, { arg }: { arg: CreateChannelMessageBody }) => {
    return createChannelMessage(id, arg, options);
  };
};
export const getCreateChannelMessageMutationKey = (id: string) =>
  [`http://localhost:41080/channels/${id}/messages`] as const;

export type CreateChannelMessageMutationResult = NonNullable<
  Awaited<ReturnType<typeof createChannelMessage>>
>;

/**
 * @summary Post a message to the channel
 */
export const useCreateChannelMessage = <
  TError =
    | CreateChannelMessage400
    | CreateChannelMessage401
    | CreateChannelMessage404
    | CreateChannelMessage409,
>(
  id: string,
  options?: {
    swr?: SWRMutationConfiguration<
      Awaited<ReturnType<typeof createChannelMessage>>,
      TError,
      Key,
      CreateChannelMessageBody,
      Awaited<ReturnType<typeof createChannelMessage>>
    > & { swrKey?: string };
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getCreateChannelMessageMutationKey(id);
  const swrFn = getCreateChannelMessageMutationFetcher(id, requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};
