/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * open-agents-platform backend REST API
 * Plain-REST surface of the agent backend (`packages/agent-backend`, port
 * 42080) as consumed by the agent frontend SPA (`packages/agent-frontend`,
 * port 42173, cross-origin via CORS).
 *
 * **Out of scope — do not add here:** the flue agent conversation endpoint
 * (`GET /agents/:name/:id`). It uses flue's Durable Streams protocol
 * (offset / reconnect / SSE observation), not standard REST, and stays on
 * `@flue/sdk` `createFlueClient`. Note that in this platform every agent
 * conversation is READ-ONLY over HTTP (GET/HEAD only, for live observation);
 * the sole write path into a conversation is `POST /channels/{id}/messages`,
 * which dispatches in-process.
 *
 * OpenAPI spec version: 0.0.0
 */

export type UpdateAgentConfig200 = {
  /** Server-generated UUID (the `configId` half of the composite agent instance id). */
  id: string;
  /** Display name chosen by the end user. Unique across the catalog — it is the label the orchestrator's delegate tool and @mentions resolve against. */
  name: string;
  /** Free-form agent instructions written by the end user (applied as a lower-trust customization section under the operator hard rules). */
  instructions: string;
  /** Job-title label (e.g. "Researcher"); absent = no role set. */
  role?: string;
  /** Creation timestamp (ISO 8601). */
  createdAt: string;
};
